blank_issues_enabled: true
contact_links:
  - name: General discussion
    url: https://elgg.org/groups/profile/15815/general-discussion
    about: Any non bug related questions can best be asked here
